# Tarea - Programación lineal

### Carolina Martinez Escalante

### Diseño de la Dieta Óptima

Se quiere producir comida para gatos de la manera más barata, no obstante se debe también asegurar que se cumplan los datos requeridos de analisis nutricional. Por lo que se quiere variar la cantidad de cada ingrediente para cumplir con los estandares nutricionales. Los requisitos que se tienen es que en $100$ gramos, se deben tener **por lo menos** $8$ gramos de proteína y $6$ gramos de grasa. Así mismo, no se debe tener más de $2$ gramos de fibra y $0.4$ gramos de sal.  

Los datos nutricionales se pueden obtener de la siguiente tabla:

Ingrediente|Proteína|Grasa|Fibra|Sal
:----|----|----|----|----
Pollo|  10.0%|08.0%|00.1%|00.2%
Carne|  20.0%|10.0%|00.5%|00.5%
Cordero|15.0%|11.0%|00.5%|00.7%
Arroz|  00.0%|01.0%|10.0%|00.2%
Trigo|  04.0%|01.0%|15.0%|00.8%
Gel|    00.0%|00.0%|00.0%|00.0%

Los costos de cada producto son:

Ingrediente|Costo por gramo
:----|----
Pollo|$\$$0.013
Carne|$\$$0.008
Cordero|$\$$0.010
Arroz|$\$$0.002
Trigo|$\$$0.005
Gel|$\$$0.001    

Lo que se busca optimizar en este caso es la cantidad de productos que se debe utilizar en la comida de gato, minimizando el costo total. Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Gramos de pollo  
+ $x_2:$ Gramos de carne  
+ $x_3:$ Gramos de cordero  
+ $x_4:$ Gramos de arroz  
+ $x_5:$ Gramos de trigo  
+ $x_6:$ Gramos de gel

La tarea consiste en plantear el problemade programación lineal que permita satisfacer las necesidades alimenticias del gato al tiempo que minimice el costo total y resolverlo con `linprog`.

Restricciones:
1. En 100 gramos debe de haber **al menos** $8 g$ de proteína


2. En 100 gramos debe de haber **al menos** $6 g$ de grasas


3. En 100 gramos debe no debe de haber **más** de $2 g$ de fibra


4. En 100 gramos debe no debe de haber **más** de $0.4 g$ de sal

In [2]:
import scipy.optimize as opt
import numpy as np

#opt.linprog?

a >= b

a -b >= 0

-b >= -a

-a <= -b

c <= d
-c >= -d

In [19]:
C=np.array([.013,.008,.01,.002,.005,.001]) 
A_ub=np.array([
    [-.10, -.20, -.15, -.00, -.04, -.00],
    [-.08, -.10,-.11,-.01,-.01,-0],
    [.001,.005,.005,.1,.15,0],
    [.002,.005,.007,.002,.008,0]
])
B_ub=np.array([-8,-6,2,.4])
A_eq=np.array([
    [1,1,1,1,1,1]
])
B_eq=np.array([100])
res = opt.linprog(C,A_ub,B_ub,A_eq,B_eq)

In [20]:
res.x

array([4.50819665e-10, 6.00000000e+01, 4.08653401e-09, 2.29072687e-08,
       3.70730008e-10, 4.00000000e+01])

In [21]:
A_ub @ res.x

array([-12. ,  -6. ,   0.3,   0.3])

In [22]:
A_eq @ res.x

array([100.])

### **Para hacer el alimento para gato de la manera más barata posible se necesitarían 60 gramos de carne y 40 gramos de gel**
### De esta manera tendríamos 12 gramos de proteína, 6 de grasa, 0.3 de fibra y 0.3 de sal, los 100 gramos solicitados y un costo de 0.52 pesos

### Problema de distribución de energía eléctrica

La Comisión Federal de Electricidad **(CFE)** dispone de cuatro plantas de generación para satisfacer la demanda diaria eléctrica en cuatro ciudades, Guadalajara, León y Morelia. Las plantas $1$, $2$ y $3$ pueden satisfacer $80$, $40$ y $60$ millones de KW al día respectivamente. Las necesidades de las ciudades de Guadalajara, León y Morelia son de $70$, $40$ y $70$ millones de Kw al día respectivamente. 


Los costos asociados al envío de suministro energético por cada millón de Kw entre cada planta y cada ciudad son los registrados en la siguiente tabla. 

-|Guadalajara|León|Morelia
:----|----|----|----
Planta 1|5|2|7
Planta 2|3|6|6
Planta 3|6|1|2

Y por último, las restricciones del problema, van a estar dadas por las capacidades de oferta y demanda de cada planta (en millones de KW) y cada ciudad.

Para simplificar la notación use las siguientes variables:

+ $x_1$: Kw (en millones) distribuidos de la Planta 1 a Guadalajara
+ $x_2$: Kw (en millones) distribuidos de la Planta 1 a León
+ $x_3$: Kw (en millones) distribuidos de la Planta 1 a Morelia
+ $x_4$: Kw (en millones) distribuidos de la Planta 2 a Guadalajara
+ $x_5$: Kw (en millones) distribuidos de la Planta 2 a León
+ $x_6$: Kw (en millones) distribuidos de la Planta 2 a Morelia
+ $x_7$: Kw (en millones) distribuidos de la Planta 3 a Guadalajara
+ $x_8$: Kw (en millones) distribuidos de la Planta 3 a León
+ $x_9$: Kw (en millones) distribuidos de la Planta 3 a Morelia

La tarea consiste en plantear el problema de programación lineal que permita satisfacer las necesidades de todas las ciudades al tiempo que minimice los costos asociados a la distribución y resolverlo con `linprog`.

In [23]:
C=np.array([5,2,7,3,6,6,6,1,2]) 
A_ub=np.array([
    [1,1,1,0,0,0,0,0,0],
    [0,0,0,1,1,1,0,0,0],
    [0,0,0,0,0,0,1,1,1]
])
B_ub=np.array([80,40,60])
A_eq=np.array([
    [1,0,0,1,0,0,1,0,0],
    [0,1,0,0,1,0,0,1,0],
    [0,0,1,0,0,1,0,0,1]
])
B_eq=np.array([70,40,70])
res =opt.linprog(C,A_ub,B_ub,A_eq,B_eq)

C:\Users\PAVILION\AppData\Local\Temp\ipykernel_13124\910029496.py:14: OptimizeWarning: Solving system with option 'cholesky':True failed. It is normal for this to happen occasionally, especially as the solution is approached. However, if you see this frequently, consider setting option 'cholesky' to False.
  res =opt.linprog(C,A_ub,B_ub,A_eq,B_eq)
C:\Users\PAVILION\AppData\Local\Temp\ipykernel_13124\910029496.py:14: OptimizeWarning: Solving system with option 'sym_pos':True failed. It is normal for this to happen occasionally, especially as the solution is approached. However, if you see this frequently, consider setting option 'sym_pos' to False.
  res =opt.linprog(C,A_ub,B_ub,A_eq,B_eq)


In [24]:
res.x

array([3.00000000e+01, 4.00000000e+01, 1.00000000e+01, 4.00000000e+01,
       1.04540829e-10, 2.57527253e-11, 5.44274848e-11, 7.26427698e-11,
       6.00000000e+01])

In [25]:
A_ub @ res.x

array([80., 40., 60.])

In [26]:
A_eq @ res.x

array([70., 40., 70.])

### Se necesitarían de la planta 1: 30 millones de Kw  a Gdl, 40 a León y 10 a Morelia. 
### De la planta 2: 40 millones de Kw a Gdl
### De la planta 3: 60 millones de Kw a Morelia

### Si se comprueba, vemos que cada planta produce lo que debería y cada ciudad recibe lo que necesita por un precio de tan solo 540 pesos